version: '3.3'
services:
    registry:
        ports:
            - '80:80'
            - '5000:5000'
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
        restart: always
        logging:
            options:
                max-size: 1g
        image: registry
